// AUTH REDUCER ACTIONS
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const NO_USER_LOADED = 'NO_USER_LOADED';
export const USER_LOAD_ERROR = 'USER_LOAD_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// CHAT REDUCER ACTIONS
export const CONNECT = "CONNECT";
export const DISCONNECT = "DISCONNECT";
export const LOAD_ROOMS = "LOAD_ROOMS";
export const ROOM_CREATED = "ROOM_CREATED";
export const EXIT_ROOM = "EXIT_ROOM";
export const JOIN_ROOM = "JOIN_ROOM";
export const LEAVE_ROOM = "LEAVE_ROOM";
export const USER_JOIN = "USER_JOIN";
export const USER_LEAVE = "USER_LEAVE";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const RECIEVE_MESSAGE = "RECIEVE_MESSAGE";
export const CHANGE_CURRENT_ROOM = "CHANGE_CURRENT_ROOM";
export const TYPING_START = "TYPING_START";
export const TYPING_END = "TYPING_END";
export const GET_ALL_PEOPLE = "GET_ALL_PEOPLE";
export const USER_STATUS_CHANGED = "USER_STATUS_CHANGED";
export const MESSAGES_LOADED = "MESSAGES_LOADED";
export const CLOSE_ROOM = "CLOSE_ROOM";

// ERROR REDUCER ACTIONS
export const NO_ERRORS = "NO_ERRORS";
export const AUTH_ERROR = 'AUTH_ERROR';
export const SERVER_ERROR = "SERVER_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// UI ACTIONS
export const OPEN_INFO_PANEL = "OPEN_INFO_PANEL";
export const CLOSE_INFO_PANEL = "CLOSE_INFO_PANEL";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const MODAL_LOADING = "MODAL_LOADING";
export const MODAL_LOADED = "MODAL_LOADED";
export const MODAL_ERROR = "MODAL_ERROR";
export const MODAL_SUCCESS = "MODAL_SUCCESS";
export const OPEN_ATTACHMENT_PANEL = "OPEN_ATTACHMENT_PANEL";
export const CLOSE_ATTACHMENT_PANEL = "CLOSE_ATTACHMENT_PANEL";
export const TOGGLE_ATTACHMENT_PANEL = "TOGGLE_ATTACHMENT_PANEL";

// PROFILE ACTIONS
export const USERNAME_UPDATE = "USERNAME_UPDATE";

// UPLOAD ACTIONS
export const PROFILE_PIC_UPLOAD = "PROFILE_PIC_UPLOAD";
export const OTHER_PROFILE_PIC_UPLOAD = "OTHER_PROFILE_PIC_UPLOAD";
export const OTHER_PROFILE_PIC_DELETE = "OTHER_PROFILE_PIC_DELETE";
export const GROUP_PIC_UPLOAD = "GROUP_PIC_UPLOAD";
export const PROFILE_PIC_DELETE = "PROFILE_PIC_DELETE";
export const GROUP_PIC_DELETE = "GROUP_PIC_DELETE";

// FILE_REDUCER
export const INIT_FILE_REDUCER = 'INIT_FILE_REDUCER';
export const ADD_FILES = "ADD_FILES";
export const REMOVE_FILE = "REMOVE_FILE";
export const CLEAR_GROUP_FILES = "CLEAR_GROUP_FILES";